server:
  host: 127.0.0.1
  port: 3000
  cors:
    - "http://127.0.0.1:4200"
    - "http://localhost:4200"
swagger:
  title: Cpu List
  description: The official API of Cpu List
  version: 1.0
  tag: cpu
  path: documentation
mongodb:
  uri: mongodb://127.0.0.1:27017/cpu
