server:
  host: 127.0.0.1
  port: 3000
  prodHost: api.cpu.cours.alasdiablo.fr
  cors:
    - "http://127.0.0.1:4200"
    - "http://localhost:4200"
    - "http://cpu.cours.alasdiablo.fr"
swagger:
  title: Cpu List
  description: The official API of Cpu List
  version: 1.0
  tag: cpu
  path: documentation
mongodb:
  uri: mongodb://localhost:27017/projet
  # uri: mongodb+srv://test:thnPZuCIqbNgXXKG@cluster0.4zvxhvl.mongodb.net/?retryWrites=true&w=majority
